//
//  Workspace.swift
//  ProjectDescriptionHelpers
//
//  Created by 진태우 on 2023/08/07.
//

import ProjectDescription

let workspace = Workspace(
    name: "App",
    projects: [
        "Projects/App",
        "Projects/Feature",
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant)
    )
)

